/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Easyshop;

import java.util.ArrayList;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

import java.awt.Desktop;  
import java.io.*;  

import java.time.LocalDateTime; // Import the LocalDateTime class
import java.time.format.DateTimeFormatter; // Import the DateTimeFormatter class

/**
 *
 * @author AMIOLA OLAGOKE
 */
public class Easyshop extends javax.swing.JFrame {

   double firstnum;
   double secondnum;
   double result;
   String operations;
   
   double[] i = new double [120];
   
   float Nigerian_Naira = 1100;
   double UD_Dollar = 1.27;
   double Kenyan_Shillings = 165.09;
   double Canadian_Dollar = 1.72;
   double Brazilian_Real = 6.36;
   double Indian_Rupee = 105.64;
   double Philippine_Peso = 71.53;
   
    public Easyshop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CalcReceiptPn = new javax.swing.JPanel();
        CalcReceiptTpn = new javax.swing.JTabbedPane();
        CalcPn = new javax.swing.JPanel();
        InputTxf = new javax.swing.JTextField();
        DeleteBtn = new javax.swing.JButton();
        CalcClearBtn = new javax.swing.JButton();
        ModBtn = new javax.swing.JButton();
        EqualBtn = new javax.swing.JButton();
        SevenBtn = new javax.swing.JButton();
        EighgtBtn = new javax.swing.JButton();
        NineBtn = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        FourBtn = new javax.swing.JButton();
        FiveBtn = new javax.swing.JButton();
        SixBtn = new javax.swing.JButton();
        MinusBtn = new javax.swing.JButton();
        OneBtn = new javax.swing.JButton();
        TwoBtn = new javax.swing.JButton();
        ThreeBtn = new javax.swing.JButton();
        MultiBtn = new javax.swing.JButton();
        ZeroBtn = new javax.swing.JButton();
        DeciBtn = new javax.swing.JButton();
        AbsBtn = new javax.swing.JButton();
        DivBtn = new javax.swing.JButton();
        ReceiptPn = new javax.swing.JPanel();
        ReceiptSpn = new javax.swing.JScrollPane();
        ReceiptTxa = new javax.swing.JTextArea();
        FoodPn = new javax.swing.JPanel();
        DoughnutCbx = new javax.swing.JCheckBox();
        CpieCbx = new javax.swing.JCheckBox();
        SauceRollCbx = new javax.swing.JCheckBox();
        DoughnutTxf = new javax.swing.JTextField();
        CpieTxf = new javax.swing.JTextField();
        SauceRollTxf = new javax.swing.JTextField();
        DrinksPn = new javax.swing.JPanel();
        DrinksCmb = new javax.swing.JComboBox<>();
        HomeDeliveryCbx = new javax.swing.JCheckBox();
        TaxCbx = new javax.swing.JCheckBox();
        DrinksLb = new javax.swing.JLabel();
        CostPn = new javax.swing.JPanel();
        CostOfDrinksLb1 = new javax.swing.JLabel();
        CostOfMealLb1 = new javax.swing.JLabel();
        CostOfDeliveryLb1 = new javax.swing.JLabel();
        CostOfDrinksLb2 = new javax.swing.JLabel();
        CostOfMealLb2 = new javax.swing.JLabel();
        CostOfDeliveryLb2 = new javax.swing.JLabel();
        ButtonsPn = new javax.swing.JPanel();
        TotalBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        ReceiptBtn = new javax.swing.JButton();
        btn_open_record = new javax.swing.JButton();
        CurrencyPn = new javax.swing.JPanel();
        CurrencyCoverterLb = new javax.swing.JLabel();
        ChooseCurrencyCmb = new javax.swing.JComboBox<>();
        ConverterTxf = new javax.swing.JTextField();
        ConvertBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        ConverterLb = new javax.swing.JLabel();
        TaxPn = new javax.swing.JPanel();
        TaxLb1 = new javax.swing.JLabel();
        TaxLb2 = new javax.swing.JLabel();
        SubTaxLb1 = new javax.swing.JLabel();
        SubTaxLb2 = new javax.swing.JLabel();
        TotalLb1 = new javax.swing.JLabel();
        TotalLb2 = new javax.swing.JLabel();
        EasyShopLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CalcReceiptPn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        InputTxf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputTxf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InputTxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTxfActionPerformed(evt);
            }
        });
        InputTxf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputTxfKeyTyped(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteBtn.setText("←");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        CalcClearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CalcClearBtn.setText("C");
        CalcClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcClearBtnActionPerformed(evt);
            }
        });

        ModBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ModBtn.setText("%");
        ModBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModBtnActionPerformed(evt);
            }
        });

        EqualBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EqualBtn.setText("=");
        EqualBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualBtnActionPerformed(evt);
            }
        });

        SevenBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SevenBtn.setText("7");
        SevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenBtnActionPerformed(evt);
            }
        });

        EighgtBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EighgtBtn.setText("8");
        EighgtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EighgtBtnActionPerformed(evt);
            }
        });

        NineBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NineBtn.setText("9");
        NineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineBtnActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setText("+");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        FourBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FourBtn.setText("4");
        FourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourBtnActionPerformed(evt);
            }
        });

        FiveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FiveBtn.setText("5");
        FiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveBtnActionPerformed(evt);
            }
        });

        SixBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SixBtn.setText("6");
        SixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixBtnActionPerformed(evt);
            }
        });

        MinusBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MinusBtn.setText("-");
        MinusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusBtnActionPerformed(evt);
            }
        });

        OneBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OneBtn.setText("1");
        OneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneBtnActionPerformed(evt);
            }
        });

        TwoBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TwoBtn.setText("2");
        TwoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoBtnActionPerformed(evt);
            }
        });

        ThreeBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ThreeBtn.setText("3");
        ThreeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeBtnActionPerformed(evt);
            }
        });

        MultiBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MultiBtn.setText("*");
        MultiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiBtnActionPerformed(evt);
            }
        });

        ZeroBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ZeroBtn.setText("0");
        ZeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroBtnActionPerformed(evt);
            }
        });

        DeciBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeciBtn.setText(".");
        DeciBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeciBtnActionPerformed(evt);
            }
        });

        AbsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AbsBtn.setText("±");
        AbsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbsBtnActionPerformed(evt);
            }
        });

        DivBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DivBtn.setText("/");
        DivBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalcPnLayout = new javax.swing.GroupLayout(CalcPn);
        CalcPn.setLayout(CalcPnLayout);
        CalcPnLayout.setHorizontalGroup(
            CalcPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalcPnLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(CalcPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InputTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CalcPnLayout.createSequentialGroup()
                        .addGroup(CalcPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CalcPnLayout.createSequentialGroup()
                                .addComponent(ZeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeciBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AbsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CalcPnLayout.createSequentialGroup()
                                .addComponent(OneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TwoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ThreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CalcPnLayout.createSequentialGroup()
                                .addComponent(FourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CalcPnLayout.createSequentialGroup()
                                .addComponent(SevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EighgtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CalcPnLayout.createSequentialGroup()
                                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CalcClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ModBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CalcPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DivBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MultiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EqualBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        CalcPnLayout.setVerticalGroup(
            CalcPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalcPnLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(InputTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalcPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalcClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EqualBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalcPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EighgtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalcPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalcPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TwoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalcPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeciBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DivBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        CalcReceiptTpn.addTab("Calculator", CalcPn);

        ReceiptTxa.setColumns(20);
        ReceiptTxa.setRows(5);
        ReceiptSpn.setViewportView(ReceiptTxa);

        javax.swing.GroupLayout ReceiptPnLayout = new javax.swing.GroupLayout(ReceiptPn);
        ReceiptPn.setLayout(ReceiptPnLayout);
        ReceiptPnLayout.setHorizontalGroup(
            ReceiptPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReceiptPnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReceiptSpn, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );
        ReceiptPnLayout.setVerticalGroup(
            ReceiptPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReceiptPnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReceiptSpn, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        CalcReceiptTpn.addTab("Receipt", ReceiptPn);

        javax.swing.GroupLayout CalcReceiptPnLayout = new javax.swing.GroupLayout(CalcReceiptPn);
        CalcReceiptPn.setLayout(CalcReceiptPnLayout);
        CalcReceiptPnLayout.setHorizontalGroup(
            CalcReceiptPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalcReceiptPnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CalcReceiptTpn)
                .addContainerGap())
        );
        CalcReceiptPnLayout.setVerticalGroup(
            CalcReceiptPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalcReceiptPnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CalcReceiptTpn, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(CalcReceiptPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 340, 430));

        FoodPn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        DoughnutCbx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoughnutCbx.setText("Doughnut");
        DoughnutCbx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoughnutCbxMouseClicked(evt);
            }
        });

        CpieCbx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CpieCbx.setText("Chicken Pie");
        CpieCbx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CpieCbxMouseClicked(evt);
            }
        });

        SauceRollCbx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SauceRollCbx.setText("Sausage Roll");
        SauceRollCbx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SauceRollCbxMouseClicked(evt);
            }
        });

        DoughnutTxf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoughnutTxf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DoughnutTxf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DoughnutTxf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DoughnutTxfKeyTyped(evt);
            }
        });

        CpieTxf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CpieTxf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CpieTxf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CpieTxf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CpieTxfKeyTyped(evt);
            }
        });

        SauceRollTxf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SauceRollTxf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SauceRollTxf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SauceRollTxf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SauceRollTxfKeyTyped(evt);
            }
        });

        DrinksPn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        DrinksCmb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DrinksCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a drink", "Water", "Fanta", "Coke", "Sprite", "Freshyo", "Chapman", " " }));
        DrinksCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinksCmbActionPerformed(evt);
            }
        });

        HomeDeliveryCbx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HomeDeliveryCbx.setText("Home Delivery");
        HomeDeliveryCbx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeDeliveryCbxMouseClicked(evt);
            }
        });
        HomeDeliveryCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeDeliveryCbxActionPerformed(evt);
            }
        });

        TaxCbx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TaxCbx.setText("Tax");
        TaxCbx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaxCbxMouseClicked(evt);
            }
        });

        DrinksLb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DrinksLb.setText("Drinks");

        javax.swing.GroupLayout DrinksPnLayout = new javax.swing.GroupLayout(DrinksPn);
        DrinksPn.setLayout(DrinksPnLayout);
        DrinksPnLayout.setHorizontalGroup(
            DrinksPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DrinksPnLayout.createSequentialGroup()
                .addGroup(DrinksPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DrinksPnLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(DrinksLb))
                    .addGroup(DrinksPnLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(HomeDeliveryCbx)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(DrinksPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaxCbx)
                    .addComponent(DrinksCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        DrinksPnLayout.setVerticalGroup(
            DrinksPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrinksPnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(DrinksPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DrinksLb)
                    .addComponent(DrinksCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(DrinksPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeDeliveryCbx)
                    .addComponent(TaxCbx))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout FoodPnLayout = new javax.swing.GroupLayout(FoodPn);
        FoodPn.setLayout(FoodPnLayout);
        FoodPnLayout.setHorizontalGroup(
            FoodPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoodPnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FoodPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FoodPnLayout.createSequentialGroup()
                        .addGroup(FoodPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SauceRollCbx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CpieCbx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DoughnutCbx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FoodPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DoughnutTxf, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(CpieTxf)
                            .addComponent(SauceRollTxf, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FoodPnLayout.createSequentialGroup()
                        .addComponent(DrinksPn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        FoodPnLayout.setVerticalGroup(
            FoodPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoodPnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FoodPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoughnutCbx)
                    .addComponent(DoughnutTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FoodPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CpieTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CpieCbx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FoodPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SauceRollCbx)
                    .addComponent(SauceRollTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DrinksPn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(FoodPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 360, 240));

        CostPn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        CostOfDrinksLb1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CostOfDrinksLb1.setText("Cost of drinks");

        CostOfMealLb1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CostOfMealLb1.setText("Cost of meal");

        CostOfDeliveryLb1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CostOfDeliveryLb1.setText("Cost of delivery");

        CostOfDrinksLb2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CostOfDrinksLb2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CostOfDrinksLb2.setText("0");
        CostOfDrinksLb2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CostOfMealLb2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CostOfMealLb2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CostOfMealLb2.setText("0");
        CostOfMealLb2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CostOfDeliveryLb2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CostOfDeliveryLb2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CostOfDeliveryLb2.setText("0");
        CostOfDeliveryLb2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout CostPnLayout = new javax.swing.GroupLayout(CostPn);
        CostPn.setLayout(CostPnLayout);
        CostPnLayout.setHorizontalGroup(
            CostPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CostPnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(CostPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CostOfDrinksLb1)
                    .addComponent(CostOfMealLb1)
                    .addComponent(CostOfDeliveryLb1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(CostPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CostPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CostOfDrinksLb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CostOfMealLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CostOfDeliveryLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        CostPnLayout.setVerticalGroup(
            CostPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CostPnLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(CostPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CostOfDrinksLb1)
                    .addComponent(CostOfDrinksLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CostPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CostOfMealLb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CostOfMealLb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(CostPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CostOfDeliveryLb1)
                    .addComponent(CostOfDeliveryLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(CostPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 360, 180));

        ButtonsPn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        TotalBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TotalBtn.setText("Total");
        TotalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalBtnMouseClicked(evt);
            }
        });
        TotalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalBtnActionPerformed(evt);
            }
        });

        ExitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        ResetBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetBtnMouseClicked(evt);
            }
        });
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        ReceiptBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReceiptBtn.setText("Receipt");
        ReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiptBtnActionPerformed(evt);
            }
        });

        btn_open_record.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_open_record.setText("Open Record");
        btn_open_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_open_recordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsPnLayout = new javax.swing.GroupLayout(ButtonsPn);
        ButtonsPn.setLayout(ButtonsPnLayout);
        ButtonsPnLayout.setHorizontalGroup(
            ButtonsPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsPnLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(TotalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(ReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btn_open_record)
                .addGap(68, 68, 68)
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        ButtonsPnLayout.setVerticalGroup(
            ButtonsPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPnLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ButtonsPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitBtn)
                    .addComponent(TotalBtn)
                    .addComponent(ResetBtn)
                    .addComponent(ReceiptBtn)
                    .addComponent(btn_open_record))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(ButtonsPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 496, 1070, 70));

        CurrencyPn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        CurrencyCoverterLb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CurrencyCoverterLb.setText("Currency Converter");

        ChooseCurrencyCmb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChooseCurrencyCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Currency", "USA", "Nigeria", "Kenya", "Canada", "Brazil", "India", "Philippine" }));
        ChooseCurrencyCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseCurrencyCmbActionPerformed(evt);
            }
        });

        ConverterTxf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConverterTxf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ConverterTxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConverterTxfActionPerformed(evt);
            }
        });
        ConverterTxf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ConverterTxfKeyTyped(evt);
            }
        });

        ConvertBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConvertBtn.setText("Convert");
        ConvertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertBtnActionPerformed(evt);
            }
        });

        ClearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        ConverterLb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConverterLb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout CurrencyPnLayout = new javax.swing.GroupLayout(CurrencyPn);
        CurrencyPn.setLayout(CurrencyPnLayout);
        CurrencyPnLayout.setHorizontalGroup(
            CurrencyPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrencyPnLayout.createSequentialGroup()
                .addGroup(CurrencyPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CurrencyPnLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(ConvertBtn)
                        .addGap(47, 47, 47)
                        .addComponent(ClearBtn))
                    .addGroup(CurrencyPnLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(CurrencyPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CurrencyCoverterLb)
                            .addComponent(ChooseCurrencyCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ConverterTxf)))
                    .addGroup(CurrencyPnLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(ConverterLb, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        CurrencyPnLayout.setVerticalGroup(
            CurrencyPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrencyPnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CurrencyCoverterLb)
                .addGap(20, 20, 20)
                .addComponent(ChooseCurrencyCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConverterTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConverterLb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(CurrencyPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClearBtn)
                    .addComponent(ConvertBtn))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(CurrencyPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 350, 240));

        TaxPn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        TaxLb1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TaxLb1.setText("Tax");

        TaxLb2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TaxLb2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TaxLb2.setText("0");
        TaxLb2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SubTaxLb1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SubTaxLb1.setText("Sub total");

        SubTaxLb2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SubTaxLb2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SubTaxLb2.setText("0");
        SubTaxLb2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TotalLb1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TotalLb1.setText("Total");

        TotalLb2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TotalLb2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TotalLb2.setText("0");
        TotalLb2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout TaxPnLayout = new javax.swing.GroupLayout(TaxPn);
        TaxPn.setLayout(TaxPnLayout);
        TaxPnLayout.setHorizontalGroup(
            TaxPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaxPnLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(TaxPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaxLb1)
                    .addComponent(SubTaxLb1)
                    .addComponent(TotalLb1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(TaxPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaxLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubTaxLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        TaxPnLayout.setVerticalGroup(
            TaxPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaxPnLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(TaxPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubTaxLb1)
                    .addComponent(SubTaxLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TaxPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaxPnLayout.createSequentialGroup()
                        .addComponent(TaxLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(TaxPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalLb1)
                            .addComponent(TotalLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(TaxLb1))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(TaxPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 350, 180));

        EasyShopLb.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        EasyShopLb.setText("EasyShop Management System");
        getContentPane().add(EasyShopLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DrinksCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinksCmbActionPerformed
        double Water = 1.00;
        double Fanta = 1.20;
        double Coke = 1.30;
        double Sprite = 1.50;
        double Freshyo = 2.00;
        double Chapman = 2.20;
        
        if (DrinksCmb.getSelectedItem().equals("Water"))
        {
        String cWater = String.format("% 2f", Water);
        CostOfDrinksLb2.setText( cWater);
        }
        
        if (DrinksCmb.getSelectedItem().equals("Fanta"))
        {
        String cFanta = String.format("% 2f", Fanta);
        CostOfDrinksLb2.setText( cFanta);
        }
        
        if (DrinksCmb.getSelectedItem().equals("Coke"))
        {
        String cCoke = String.format("% 2f", Coke);
        CostOfDrinksLb2.setText( cCoke);
        }
        
        if (DrinksCmb.getSelectedItem().equals("Sprite"))
        {
        String cSprite = String.format("% 2f", Sprite);
        CostOfDrinksLb2.setText( cSprite);
        }
        
        if (DrinksCmb.getSelectedItem().equals("Freshyo"))
        {
        String cFreshyo = String.format("% 2f", Freshyo);
        CostOfDrinksLb2.setText( cFreshyo);
        }
        
        if (DrinksCmb.getSelectedItem().equals("Chapman"))
        {
        String cChapman = String.format("% 2f", Chapman);
        CostOfDrinksLb2.setText( cChapman);
        }
     
        if (DrinksCmb.getSelectedItem().equals("Select a drink"))
        {
        CostOfDrinksLb2.setText( null);
        }
    }//GEN-LAST:event_DrinksCmbActionPerformed

    private void ZeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroBtnActionPerformed
        String Enternumber = InputTxf.getText() + ZeroBtn.getText();
        InputTxf.setText(Enternumber);
    }//GEN-LAST:event_ZeroBtnActionPerformed

    private void OneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneBtnActionPerformed
        String Enternumber = InputTxf.getText() + OneBtn.getText();
        InputTxf.setText(Enternumber);
    }//GEN-LAST:event_OneBtnActionPerformed

    private void TwoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoBtnActionPerformed
        String Enternumber = InputTxf.getText() + TwoBtn.getText();
        InputTxf.setText(Enternumber);
    }//GEN-LAST:event_TwoBtnActionPerformed

    private void ThreeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeBtnActionPerformed
        String Enternumber = InputTxf.getText() + ThreeBtn.getText();
        InputTxf.setText(Enternumber);
    }//GEN-LAST:event_ThreeBtnActionPerformed

    private void FourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourBtnActionPerformed
        String Enternumber = InputTxf.getText() + FourBtn.getText();
        InputTxf.setText(Enternumber);
    }//GEN-LAST:event_FourBtnActionPerformed

    private void FiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveBtnActionPerformed
        String Enternumber = InputTxf.getText() + FiveBtn.getText();
        InputTxf.setText(Enternumber);
    }//GEN-LAST:event_FiveBtnActionPerformed

    private void SixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixBtnActionPerformed
        String Enternumber = InputTxf.getText() + SixBtn.getText();
        InputTxf.setText(Enternumber);
    }//GEN-LAST:event_SixBtnActionPerformed

    private void SevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenBtnActionPerformed
        String Enternumber = InputTxf.getText() + SevenBtn.getText();
        InputTxf.setText(Enternumber);
    }//GEN-LAST:event_SevenBtnActionPerformed

    private void EighgtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EighgtBtnActionPerformed
        String Enternumber = InputTxf.getText() + EighgtBtn.getText();
        InputTxf.setText(Enternumber);
    }//GEN-LAST:event_EighgtBtnActionPerformed

    private void NineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineBtnActionPerformed
        String Enternumber = InputTxf.getText() + NineBtn.getText();
        InputTxf.setText(Enternumber);
    }//GEN-LAST:event_NineBtnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        firstnum = Double.parseDouble(InputTxf.getText());
        InputTxf.setText("");
        operations ="+";
    }//GEN-LAST:event_jButton8ActionPerformed

    private void MinusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusBtnActionPerformed
        firstnum = Double.parseDouble(InputTxf.getText());
        InputTxf.setText("");
        operations ="-";
    }//GEN-LAST:event_MinusBtnActionPerformed

    private void MultiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiBtnActionPerformed
        firstnum = Double.parseDouble(InputTxf.getText());
        InputTxf.setText("");
        operations ="*";
    }//GEN-LAST:event_MultiBtnActionPerformed

    private void DivBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivBtnActionPerformed
        firstnum = Double.parseDouble(InputTxf.getText());
        InputTxf.setText("");
        operations ="/";
    }//GEN-LAST:event_DivBtnActionPerformed

    private void AbsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbsBtnActionPerformed
         double ops = Double.parseDouble(String.valueOf(InputTxf.getText()));
        ops = ops * (-1);
        InputTxf.setText(String.valueOf(ops));
    }//GEN-LAST:event_AbsBtnActionPerformed

    private void DeciBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeciBtnActionPerformed
        if (!InputTxf.getText().contains("."))
        {
        InputTxf.setText(InputTxf.getText() + DeciBtn.getText());
        }                                     
    }//GEN-LAST:event_DeciBtnActionPerformed

    private void InputTxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTxfActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
       String bsp = null;
        
        if (InputTxf.getText().length() > 0)
        {
            StringBuilder strB = new StringBuilder(InputTxf.getText());
            strB.deleteCharAt(InputTxf.getText().length() - 1);
            bsp = strB.toString();
            InputTxf.setText(bsp);
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void CalcClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcClearBtnActionPerformed
        InputTxf.setText("");
    }//GEN-LAST:event_CalcClearBtnActionPerformed

    private void EqualBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualBtnActionPerformed
        String answer;
        secondnum = Double.parseDouble(InputTxf.getText());
        if (null != operations)
        switch (operations) {
           case "+" -> {
               result = firstnum + secondnum;
               answer = String.format("%.0f", result);
               InputTxf.setText(answer);
            }
           case "-" -> {
               result = firstnum - secondnum;
               answer = String.format("%.0f", result);
               InputTxf.setText(answer);
            }
           case "*" -> {
               result = firstnum * secondnum;
               answer = String.format("%.0f", result);
               InputTxf.setText(answer);
            }
           case "/" -> {
               result = firstnum / secondnum;
               answer = String.format("%.0f", result);
               InputTxf.setText(answer);
            }
           case "%" -> {
               result = firstnum % secondnum;
               answer = String.format("%.0f", result);
               InputTxf.setText(answer);
            }
           default -> {
               break;
            }
       }
                             
    }//GEN-LAST:event_EqualBtnActionPerformed

    private void ModBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModBtnActionPerformed
        firstnum = Double.parseDouble(InputTxf.getText());
        InputTxf.setText("");
        operations ="%";
    }//GEN-LAST:event_ModBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        ConverterTxf.setText("");
        ConverterLb.setText("");
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void ConvertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertBtnActionPerformed
        double British_Pounds = Double.parseDouble(ConverterTxf.getText());
        if (ChooseCurrencyCmb.getSelectedItem().equals("Nigeria"))
        {
        String cConvert1 = String.format("N % 2f", British_Pounds * Nigerian_Naira);
        ConverterLb.setText( cConvert1);
        }    
        
        if (ChooseCurrencyCmb.getSelectedItem().equals("USA"))
        {
        String cConvert2 = String.format("$ % 2f", British_Pounds * UD_Dollar);
        ConverterLb.setText( cConvert2);
        }    
        
        if (ChooseCurrencyCmb.getSelectedItem().equals("Kenya"))
        {
        String cConvert3 = String.format("kS % 2f", British_Pounds * Kenyan_Shillings);
        ConverterLb.setText( cConvert3);
        }    
        
        if (ChooseCurrencyCmb.getSelectedItem().equals("Canada"))
        {
        String cConvert4 = String.format("CD % 2f", British_Pounds * Canadian_Dollar);
        ConverterLb.setText( cConvert4);
        }    
        
        if (ChooseCurrencyCmb.getSelectedItem().equals("Brazil"))
        {
        String cConvert5 = String.format("BR % 2f", British_Pounds * Brazilian_Real);
        ConverterLb.setText( cConvert5);
        }
        
        if (ChooseCurrencyCmb.getSelectedItem().equals("India"))
        {
        String cConvert6 = String.format("IR % 2f", British_Pounds * Indian_Rupee);
        ConverterLb.setText( cConvert6);
        }
        
        if (ChooseCurrencyCmb.getSelectedItem().equals("Philippine"))
        {
        String cConvert7 = String.format("PP % 2f", British_Pounds * Philippine_Peso);
        ConverterLb.setText( cConvert7);
        }
    }//GEN-LAST:event_ConvertBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void HomeDeliveryCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeDeliveryCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeDeliveryCbxActionPerformed

    private void HomeDeliveryCbxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeDeliveryCbxMouseClicked
        double iDelivery = 3.39;
        
        if (HomeDeliveryCbx.isSelected())
        {
        String pDelivery = String.format("%.2f" , iDelivery);
        CostOfDeliveryLb2.setText(pDelivery);
        }
        else
        {
        CostOfDeliveryLb2.setText(null);
        }
    }//GEN-LAST:event_HomeDeliveryCbxMouseClicked

    private void TaxCbxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaxCbxMouseClicked
        double iTax = 1.50;
        
        if (TaxCbx.isSelected())
        {
        String pTax = String.format("%.2f" , iTax);
        TaxLb2.setText(pTax);
        }
        else
        {
        TaxLb2.setText(null);
        }
    }//GEN-LAST:event_TaxCbxMouseClicked

    private void ResetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetBtnMouseClicked
        TotalLb2.setText("0");
        SubTaxLb2.setText("0");
        TaxLb2.setText("0");
        CostOfDeliveryLb2.setText("0");
        CostOfMealLb2.setText("0");
        ConverterLb.setText(null);
        ConverterTxf.setText(null);
        DoughnutTxf.setText("0");
        CpieTxf.setText("0");
        SauceRollTxf.setText("0");
        InputTxf.setText(null);
        ReceiptTxa.setText(null);
        ChooseCurrencyCmb.setSelectedItem("Choose Currency");
       // ChooseCurrencyCmb.setSelectedIndex(0);
        DrinksCmb.setSelectedItem("Select a drink");
        CostOfDrinksLb2.setText("0");
        TaxCbx.setSelected(false);
        HomeDeliveryCbx.setSelected(false);
        DoughnutCbx.setSelected(false);
        CpieCbx.setSelected(false);
        SauceRollCbx.setSelected(false);
    }//GEN-LAST:event_ResetBtnMouseClicked

    private void DoughnutCbxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoughnutCbxMouseClicked
        double cMeal = Double.parseDouble(CostOfMealLb2.getText());
        double Doughnut = Double.parseDouble(DoughnutTxf.getText());
        double iDoughnut = 3.00;
        
               if (DoughnutCbx.isSelected())
               {
               i[0] = (Doughnut * iDoughnut) + cMeal;
               String pMeal = String.format("%.2f", i[0]);
               CostOfMealLb2.setText(pMeal);
               }
    }//GEN-LAST:event_DoughnutCbxMouseClicked

    private void CpieCbxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CpieCbxMouseClicked
        double cMeal = Double.parseDouble(CostOfMealLb2.getText());
        double Chickpie = Double.parseDouble(CpieTxf.getText());
        double iChickpie = 2.00;
        
               if (CpieCbx.isSelected())
               {
               i[1] = (Chickpie * iChickpie) + cMeal;
               String pMeal = String.format("%.2f", i[1]);
               CostOfMealLb2.setText(pMeal);
               }
    }//GEN-LAST:event_CpieCbxMouseClicked

    private void SauceRollCbxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SauceRollCbxMouseClicked
        double cMeal = Double.parseDouble(CostOfMealLb2.getText());
        double Sauceroll = Double.parseDouble(SauceRollTxf.getText());
        double iSauceroll = 2.50;
        
               if (SauceRollCbx.isSelected())
               {
               i[2] = (Sauceroll * iSauceroll) + cMeal;
               String pMeal = String.format("%.2f", i[2]);
               CostOfMealLb2.setText(pMeal);
               }
    }//GEN-LAST:event_SauceRollCbxMouseClicked

    private void TotalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalBtnMouseClicked
        
    }//GEN-LAST:event_TotalBtnMouseClicked

    private void TotalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalBtnActionPerformed
        double cTotal1 = Double.parseDouble(CostOfDrinksLb2.getText());
        double cTotal2 = Double.parseDouble(CostOfMealLb2.getText());
        double cTotal3 = Double.parseDouble(CostOfDeliveryLb2.getText());
        double cTotal4 = Double.parseDouble(TaxLb2.getText());
        
        double subTotal = (cTotal1 + cTotal2 + cTotal3);
        double allTotal = (cTotal1 + cTotal2 + cTotal3 + cTotal4);
        
        String sTotal = String.format("£%.2f", subTotal);
        SubTaxLb2.setText(sTotal);
        
        String aTotal = String.format("£%.2f",allTotal);
        TotalLb2.setText(aTotal);  
        
        
        //Append items bought to the file
        
        //LocalDateTime myDateObject 
                
            LocalDateTime myDateObj = LocalDateTime.now();
            DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm:ss");

            String formattedDate = myDateObj.format(myFormatObj);
          //  System.out.println(formattedDate);
        
        double Qty1 = Double.parseDouble(DoughnutTxf.getText());
        double Qty2 = Double.parseDouble(CpieTxf.getText());
        double Qty3 = Double.parseDouble(SauceRollTxf.getText());
        
        double price1 = (Qty1*3.0);
        double price2 = (Qty2*2.0);
        double price3 = (Qty3*2.5);
        
         String path = System.getProperty("user.dir") + "\\src\\filename.txt";
        String text = formattedDate + "\n Easyshop Management System\n" 
                +"=========================================\n\n"
                +"Snacks\t\t" + "Price\n"
                +"Doughnut\t\t"  + price1 + "\n"
                +"Chicken pie\t\t"  + price2 +"\n"
                +"Sausage roll\t\t"  + price3 +"\n\n"
                +"Cost of drinks\t\t" + cTotal1 +"\t"
                +"\t\t" + 1 + "\t" + 2+ "\n"
                +"=========================================\n\n"
                +"Subtotal\t\t" + subTotal + "\n"
                +"Tax\t\t" + cTotal4 + "\n"  
                +"Total\t\t" + allTotal + "\n\n"
                +"=========================================\n\n"
                +"Thank you for patronising us, come again soon\n\n\n";
        
        
        

        try {
            Files.write(Paths.get(path), text.getBytes(), StandardOpenOption.APPEND);
        } catch (IOException e) {
        }
    
        
    }//GEN-LAST:event_TotalBtnActionPerformed

    private void ChooseCurrencyCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseCurrencyCmbActionPerformed
        // TODO add your handling code here:
    ArrayList<String> currency = new ArrayList<String>();
    currency.add("USA");
    currency.add("Nigeria");
    currency.add("Kenya");
    currency.add("Canada");
    currency.add("Brazil");
    currency.add("India");
    currency.add("Philipine");
    System.out.println(currency);
        
        
    }//GEN-LAST:event_ChooseCurrencyCmbActionPerformed

    private void ReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiptBtnActionPerformed
        double Qty1 = Double.parseDouble(DoughnutTxf.getText());
        double Qty2 = Double.parseDouble(CpieTxf.getText());
        double Qty3 = Double.parseDouble(SauceRollTxf.getText());
        
        double price1 = (Qty1*3.0);
        double price2 = (Qty2*2.0);
        double price3 = (Qty3*2.5);
        
        double cTotal1 = Double.parseDouble(CostOfDrinksLb2.getText());
        double cTotal2 = Double.parseDouble(CostOfMealLb2.getText());
        double cTotal3 = Double.parseDouble(CostOfDeliveryLb2.getText());
        double cTotal4 = Double.parseDouble(TaxLb2.getText());
        
        double subTotal = (cTotal1 + cTotal2 + cTotal3);
        double allTotal = (cTotal1 + cTotal2 + cTotal3 + cTotal4);
        
        
        ReceiptTxa.append("Easyshop Management System\n" 
                +"=========================================\n\n"
                +"Snacks\t\t" + "Price\n"
                +"Doughnut\t\t"  + price1 + "\n"
                +"Chicken pie\t\t"  + price2 +"\n"
                +"Sausage roll\t\t"  + price3 +"\n\n"
                +"Cost of drinks\t\t" + cTotal1 +"\t"
                +"\t\t" + 1 + "\t" + 2+ "\n"
                +"=========================================\n\n"
                +"Subtotal\t\t" + subTotal + "\n"
                +"Tax\t\t" + cTotal4 + "\n"  
                +"Total\t\t" + allTotal + "\n\n"
                +"=========================================\n\n"
                +"Thank you for patronising us, come again soon\n\n\n");
        
    }//GEN-LAST:event_ReceiptBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void ConverterTxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConverterTxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConverterTxfActionPerformed

    private void DoughnutTxfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DoughnutTxfKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
           evt.consume();
        }
    }//GEN-LAST:event_DoughnutTxfKeyTyped

    private void CpieTxfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CpieTxfKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
           evt.consume();
        }
    }//GEN-LAST:event_CpieTxfKeyTyped

    private void SauceRollTxfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SauceRollTxfKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
           evt.consume();
        }
    }//GEN-LAST:event_SauceRollTxfKeyTyped

    private void ConverterTxfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConverterTxfKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c) && evt.isAltDown()){
           evt.consume();
        }
    }//GEN-LAST:event_ConverterTxfKeyTyped

    private void InputTxfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputTxfKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
           evt.consume();
        }
       
    }//GEN-LAST:event_InputTxfKeyTyped

    private void btn_open_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_open_recordActionPerformed
        // TODO add your handling code here:
        
        
        try  
{  
//constructor of file class having file as argument  
String path = System.getProperty("user.dir") + "\\src\\filename.txt";
File file = new File(path);   
if(!Desktop.isDesktopSupported())//check if Desktop is supported by Platform or not  
{  
System.out.println("not supported");  
return;  
}  
Desktop desktop = Desktop.getDesktop();  
if(file.exists())         //checks file exists or not  
desktop.open(file);              //opens the specified file  
}  
catch(Exception e)  
{  
e.printStackTrace();  
}  
        
        
    }//GEN-LAST:event_btn_open_recordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Easyshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Easyshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Easyshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Easyshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Easyshop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbsBtn;
    private javax.swing.JPanel ButtonsPn;
    private javax.swing.JButton CalcClearBtn;
    private javax.swing.JPanel CalcPn;
    private javax.swing.JPanel CalcReceiptPn;
    private javax.swing.JTabbedPane CalcReceiptTpn;
    private javax.swing.JComboBox<String> ChooseCurrencyCmb;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton ConvertBtn;
    private javax.swing.JLabel ConverterLb;
    private javax.swing.JTextField ConverterTxf;
    private javax.swing.JLabel CostOfDeliveryLb1;
    private javax.swing.JLabel CostOfDeliveryLb2;
    private javax.swing.JLabel CostOfDrinksLb1;
    private javax.swing.JLabel CostOfDrinksLb2;
    private javax.swing.JLabel CostOfMealLb1;
    private javax.swing.JLabel CostOfMealLb2;
    private javax.swing.JPanel CostPn;
    private javax.swing.JCheckBox CpieCbx;
    private javax.swing.JTextField CpieTxf;
    private javax.swing.JLabel CurrencyCoverterLb;
    private javax.swing.JPanel CurrencyPn;
    private javax.swing.JButton DeciBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton DivBtn;
    private javax.swing.JCheckBox DoughnutCbx;
    private javax.swing.JTextField DoughnutTxf;
    private javax.swing.JComboBox<String> DrinksCmb;
    private javax.swing.JLabel DrinksLb;
    private javax.swing.JPanel DrinksPn;
    private javax.swing.JLabel EasyShopLb;
    private javax.swing.JButton EighgtBtn;
    private javax.swing.JButton EqualBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton FiveBtn;
    private javax.swing.JPanel FoodPn;
    private javax.swing.JButton FourBtn;
    private javax.swing.JCheckBox HomeDeliveryCbx;
    private javax.swing.JTextField InputTxf;
    private javax.swing.JButton MinusBtn;
    private javax.swing.JButton ModBtn;
    private javax.swing.JButton MultiBtn;
    private javax.swing.JButton NineBtn;
    private javax.swing.JButton OneBtn;
    private javax.swing.JButton ReceiptBtn;
    private javax.swing.JPanel ReceiptPn;
    private javax.swing.JScrollPane ReceiptSpn;
    private javax.swing.JTextArea ReceiptTxa;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JCheckBox SauceRollCbx;
    private javax.swing.JTextField SauceRollTxf;
    private javax.swing.JButton SevenBtn;
    private javax.swing.JButton SixBtn;
    private javax.swing.JLabel SubTaxLb1;
    private javax.swing.JLabel SubTaxLb2;
    private javax.swing.JCheckBox TaxCbx;
    private javax.swing.JLabel TaxLb1;
    private javax.swing.JLabel TaxLb2;
    private javax.swing.JPanel TaxPn;
    private javax.swing.JButton ThreeBtn;
    private javax.swing.JButton TotalBtn;
    private javax.swing.JLabel TotalLb1;
    private javax.swing.JLabel TotalLb2;
    private javax.swing.JButton TwoBtn;
    private javax.swing.JButton ZeroBtn;
    private javax.swing.JButton btn_open_record;
    private javax.swing.JButton jButton8;
    // End of variables declaration//GEN-END:variables
}
